import Foundation
import Testing

@testable import KeepoCore

/// UTC throughout, matching the calendar every date-only value in this app
/// is decoded and compared in.
private let calendar: Calendar = {
    var calendar = Calendar(identifier: .gregorian)
    calendar.timeZone = TimeZone(identifier: "UTC") ?? .gmt
    return calendar
}()

private func date(_ year: Int, _ month: Int, _ day: Int) -> Date {
    calendar.date(from: DateComponents(year: year, month: month, day: day)) ?? Date()
}

@Suite("MetricGranularity")
struct MetricGranularityTests {
    @Test("A bucket start is the first instant of the period the date falls in")
    func bucketStart() {
        #expect(MetricGranularity.month.bucketStart(for: date(2026, 5, 17), calendar: calendar) == date(2026, 5, 1))
        #expect(MetricGranularity.year.bucketStart(for: date(2026, 5, 17), calendar: calendar) == date(2026, 1, 1))
    }

    @Test("A closed bucket evaluates at its own last day")
    func evaluationDateOfClosedBucket() {
        let asOf = MetricGranularity.month.evaluationDate(
            forBucket: date(2026, 5, 1), now: date(2026, 8, 25), calendar: calendar
        )
        #expect(asOf == date(2026, 5, 31))
    }

    /// The clamp that stops a chart drawing a flat run of identical future
    /// points: December's net worth evaluated in August is today's number
    /// wearing December's label.
    @Test("The current bucket evaluates at today, never at its future end")
    func evaluationDateOfOpenBucket() {
        let now = date(2026, 8, 25)
        #expect(MetricGranularity.month.evaluationDate(forBucket: date(2026, 8, 1), now: now, calendar: calendar) == now)
        #expect(MetricGranularity.year.evaluationDate(forBucket: date(2026, 1, 1), now: now, calendar: calendar) == now)
    }

    @Test("Buckets are generated by stepping, so an empty period still has an axis slot")
    func bucketsAreContiguous() {
        let buckets = MetricGranularity.month.buckets(
            from: date(2026, 1, 15), through: date(2026, 4, 2), calendar: calendar
        )
        #expect(buckets == [date(2026, 1, 1), date(2026, 2, 1), date(2026, 3, 1), date(2026, 4, 1)])
    }

    @Test("A single-bucket span counts as one, not zero")
    func bucketCountIsInclusive() {
        #expect(
            MetricGranularity.month.bucketCount(
                from: date(2026, 5, 3), through: date(2026, 5, 28), calendar: calendar
            ) == 1
        )
        #expect(
            MetricGranularity.month.bucketCount(
                from: date(2025, 12, 1), through: date(2026, 2, 1), calendar: calendar
            ) == 3
        )
    }

    @Test("Week labels name the month once, or twice when the week straddles two")
    func weekLabels() {
        // 2026-05-04 is a Monday; that week sits entirely inside May.
        let inside = MetricGranularity.week.axisLabel(
            for: date(2026, 5, 6), calendar: calendar, locale: Locale(identifier: "en_GB")
        )
        #expect(inside.contains("May"))
        #expect(!inside.dropFirst().contains("Apr"))

        // The week containing 2026-04-30 crosses into May.
        let straddling = MetricGranularity.week.axisLabel(
            for: date(2026, 4, 30), calendar: calendar, locale: Locale(identifier: "en_GB")
        )
        #expect(straddling.contains("Apr"))
        #expect(straddling.contains("May"))
    }

    @Test("isCurrent is true only for the bucket containing now")
    func isCurrent() {
        let now = date(2026, 8, 25)
        #expect(MetricGranularity.month.isCurrent(bucket: date(2026, 8, 3), now: now, calendar: calendar))
        #expect(!MetricGranularity.month.isCurrent(bucket: date(2026, 7, 31), now: now, calendar: calendar))
    }
}

@Suite("MetricZoom")
struct MetricZoomTests {
    private let monthYear: [MetricGranularity] = [.month, .year]
    private let all: [MetricGranularity] = [.week, .month, .year]

    @Test("A span inside monthly's band stays monthly")
    func staysMonthly() {
        #expect(MetricZoom.granularity(forVisibleMonths: 12, current: .month, allowed: monthYear) == .month)
        #expect(MetricZoom.granularity(forVisibleMonths: 18, current: .month, allowed: monthYear) == .month)
    }

    @Test("Zooming out past 18 months escalates to yearly")
    func escalatesToYearly() {
        #expect(MetricZoom.granularity(forVisibleMonths: 19, current: .month, allowed: monthYear) == .year)
    }

    /// The whole reason the two thresholds differ. A pinch that settles
    /// between 15 and 18 months keeps whichever resolution it arrived at,
    /// instead of flipping back and forth across a single line.
    @Test("Hysteresis: 16 months keeps whichever granularity it arrived at")
    func hysteresis() {
        #expect(MetricZoom.granularity(forVisibleMonths: 16, current: .year, allowed: monthYear) == .year)
        #expect(MetricZoom.granularity(forVisibleMonths: 16, current: .month, allowed: monthYear) == .month)
    }

    @Test("Zooming in past 15 months returns to monthly")
    func refinesToMonthly() {
        #expect(MetricZoom.granularity(forVisibleMonths: 14, current: .year, allowed: monthYear) == .month)
    }

    @Test("Weekly is only reachable where it is allowed")
    func weeklyOnlyWhenAllowed() {
        #expect(MetricZoom.granularity(forVisibleMonths: 1, current: .month, allowed: all) == .week)
        #expect(MetricZoom.granularity(forVisibleMonths: 1, current: .month, allowed: monthYear) == .month)
    }

    @Test("Weekly escalates to monthly past two months")
    func weeklyEscalates() {
        #expect(MetricZoom.granularity(forVisibleMonths: 3, current: .week, allowed: all) == .month)
        #expect(MetricZoom.granularity(forVisibleMonths: 1.8, current: .week, allowed: all) == .week)
    }

    @Test("Without a current granularity, the span alone decides")
    func spanOnly() {
        #expect(MetricZoom.granularity(forVisibleMonths: 6, allowed: monthYear) == .month)
        #expect(MetricZoom.granularity(forVisibleMonths: 40, allowed: monthYear) == .year)
    }
}

@Suite("SeriesWindow")
struct SeriesWindowTests {
    @Test("A window pads the visible range by one visible width each side")
    func padding() {
        let window = SeriesWindow.covering(
            visibleFrom: date(2026, 5, 1), visibleThrough: date(2026, 10, 1),
            granularity: .month, limit: nil, calendar: calendar
        )
        // Six visible months, so six months of padding either side.
        #expect(window.from == date(2025, 11, 1))
        #expect(window.through == date(2027, 4, 1))
    }

    @Test("Padding is clamped to the data that exists")
    func clampedToLimit() {
        let window = SeriesWindow.covering(
            visibleFrom: date(2026, 5, 1), visibleThrough: date(2026, 10, 1), granularity: .month,
            limit: date(2026, 3, 1) ... date(2026, 11, 1), calendar: calendar
        )
        #expect(window.from == date(2026, 3, 1))
        #expect(window.through == date(2026, 11, 1))
    }

    @Test("A loaded window covers a visible range inside it and not one outside")
    func covers() {
        let window = SeriesWindow(granularity: .month, from: date(2026, 1, 1), through: date(2026, 12, 1))
        #expect(window.covers(visibleFrom: date(2026, 3, 1), visibleThrough: date(2026, 6, 1), granularity: .month))
        #expect(!window.covers(visibleFrom: date(2025, 12, 1), visibleThrough: date(2026, 6, 1), granularity: .month))
    }

    /// A resolution change is never a subset — the buckets are different
    /// values, so the points themselves have to be recomputed.
    @Test("A different granularity is never covered")
    func granularityChangeIsNeverCovered() {
        let window = SeriesWindow(granularity: .month, from: date(2026, 1, 1), through: date(2026, 12, 1))
        #expect(!window.covers(visibleFrom: date(2026, 3, 1), visibleThrough: date(2026, 6, 1), granularity: .year))
    }
}

@Suite("CurrencyRegion")
struct CurrencyRegionTests {
    /// This suite tests the **rule**, not a list of currencies.
    ///
    /// "Every supported currency has a flag" can only be answered where the
    /// artwork is — `CurrencyFlagAssetTests` in the app target owns that list
    /// and checks each name against the real bundle. Keeping a second copy
    /// here would be two lists free to disagree, and the one without a bundle
    /// is the one that cannot actually catch a missing flag.
    @Test("The euro belongs to the union, not to a country")
    func euroOverride() {
        #expect(CurrencyRegion.region(for: "EUR") == "EU")
        #expect(CurrencyRegion.flagAssetName(for: "EUR") == "flag-eu")
    }

    @Test("A currency code is its region plus one letter")
    func twoLetterRule() {
        #expect(CurrencyRegion.region(for: "USD") == "US")
        #expect(CurrencyRegion.flagAssetName(for: "USD") == "flag-us")
        #expect(CurrencyRegion.flagAssetName(for: "jpy") == "flag-jp")
        #expect(CurrencyRegion.flagAssetName(for: "CHF") == "flag-ch")
    }

    /// Better no flag than a wrong one: `XAU` is gold, not a country.
    @Test("Supranational and metal codes have no flag")
    func noFlagRatherThanAWrongOne() {
        #expect(CurrencyRegion.region(for: "XAU") == nil)
        #expect(CurrencyRegion.region(for: "XDR") == nil)
        #expect(CurrencyRegion.flagAssetName(for: "") == nil)
        #expect(CurrencyRegion.flagAssetName(for: "12A") == nil)
    }

    /// The prefix is what keeps a two-letter region from colliding with one
    /// of the app's own asset names, so it is part of the contract the
    /// catalogue is generated against.
    @Test("Every flag name is prefixed and lowercased")
    func namesArePrefixedAndLowercased() {
        for code in ["USD", "eur", "GbP", "SEK", "ZAR"] {
            guard let name = CurrencyRegion.flagAssetName(for: code) else {
                Issue.record("no flag for \(code)")
                continue
            }
            #expect(name.hasPrefix("flag-"))
            #expect(name == name.lowercased())
            #expect(name.count == "flag-".count + 2)
        }
    }
}

@Suite("MetricKind")
struct MetricKindTests {
    /// The cut is average-vs-sum, not flow-vs-balance. An FX rate is
    /// computed over a period like a cashflow is, but it is an average, so
    /// a part-finished month is directly comparable to a whole one — and
    /// the widget should open reading it. Cashflow's part-finished month is
    /// not, and its widget should open on the last closed one.
    @Test("Only period sums are partial in the current bucket")
    func partialBuckets() {
        #expect(MetricKind.cashflowNet.currentBucketIsPartial)
        #expect(MetricKind.moneyIn.currentBucketIsPartial)
        #expect(MetricKind.moneyOut.currentBucketIsPartial)
        #expect(!MetricKind.fxRate.currentBucketIsPartial)
        #expect(!MetricKind.netWorth.currentBucketIsPartial)
        #expect(!MetricKind.invested.currentBucketIsPartial)
        #expect(!MetricKind.investingRatio.currentBucketIsPartial)
    }
}
