import KeepoCore
import SwiftUI

/// Report screen four: the household's tags, and the chance to prune the
/// duplicates two people inevitably arrive with.
///
/// Tags are the one thing here nobody chose to share. Sharing an account
/// shares every tag on it automatically (`can_read_tag` derives visibility
/// from `can_read_account`), so the first time either member sees the pooled
/// list is now — and it is usually where "Holiday" meets "Holidays".
///
/// **Deleting one asks where its transactions go.** A tag is not decoration;
/// it is the only record that a transaction belonged to something the user was
/// tracking. Dropping the label off somebody's history because the owner
/// thought two names looked alike is not a tidy-up, it is data loss, so the
/// destination is a required part of the act rather than an afterthought.
struct HouseholdReportTags: View {
    let session: SessionStore
    let snapshot: HouseholdSnapshot
    var onChange: () -> Void

    /// The generated `PublicSchema` types are plain `Codable` structs with no
    /// `Identifiable` conformance — every list in the app iterates them by an
    /// explicit key path for that reason. `sheet(item:)` needs one, so the
    /// selection is wrapped rather than the generated type retrofitted: it is
    /// regenerated by `supabase gen types swift` after every migration, and an
    /// extension on it would be the only hand-written thing in that file's
    /// orbit.
    @State private var pruning: PruningTag?
    @State private var isExpanded = true
    @State private var errorMessage: String?

    var body: some View {
        VStack(spacing: AppTheme.Spacing.l) {
            countCard
            listCard
            if let errorMessage { FormErrorText(message: errorMessage) }
        }
        .sheet(item: $pruning) { selected in
            TagRetagSheet(
                session: session,
                tag: selected.tag,
                options: snapshot.tags.filter { $0.id != selected.tag.id },
                onDone: {
                    pruning = nil
                    onChange()
                }
            )
            .presentationDetents([.medium])
            .presentationDragIndicator(.visible)
        }
    }

    private var countCard: some View {
        HouseholdCard(
            title: "Household tags",
            subtitle: "Every tag on a shared account, from both of you. Delete a duplicate and "
                + "you'll choose which tag its transactions move to."
        ) {
            HouseholdMetric(
                value: snapshot.tags.count,
                label: snapshot.tags.count == 1 ? "Tag" : "Tags",
                tint: AppTheme.Palette.tagTint
            )
        }
    }

    private var listCard: some View {
        HouseholdCard(title: "All tags") {
            HouseholdDisclosure(
                title: "Tags", count: snapshot.tags.count, isExpanded: $isExpanded
            ) {
                VStack(spacing: AppTheme.Spacing.xs) {
                    ForEach(snapshot.tags, id: \.id) { tag in
                        HStack(spacing: AppTheme.Spacing.m) {
                            TagChip(name: tag.name)
                            Spacer(minLength: AppTheme.Spacing.s)
                            RemoveBadge(
                                label: "Delete tag \(tag.name)", diameter: AppTheme.Size.glyphSmall
                            ) {
                                pruning = PruningTag(tag: tag)
                            }
                        }
                        .padding(.vertical, AppTheme.Spacing.xxs)
                    }
                }
                .padding(.bottom, AppTheme.Spacing.s)
            }
        }
    }
}

private struct PruningTag: Identifiable {
    let tag: PublicSchema.TagsSelect
    var id: UUID { tag.id }
}

/// "This tag is going. Where do its transactions land?"
///
/// The destination is not optional. `delete_tag_retagging` accepts a null and
/// falls back to the plain delete the Tags screen has always done, but this
/// screen never sends one: the whole reason a tag is being removed *here* is
/// that another tag already means the same thing.
private struct TagRetagSheet: View {
    let session: SessionStore
    let tag: PublicSchema.TagsSelect
    let options: [PublicSchema.TagsSelect]
    var onDone: () -> Void

    @Environment(\.dismiss) private var dismiss

    @State private var destination: PublicSchema.TagsSelect?
    @State private var isSaving = false
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.Palette.bgCanvas.ignoresSafeArea()
                ScrollView {
                    VStack(alignment: .leading, spacing: AppTheme.Spacing.l) {
                        header
                        picker
                        if let errorMessage { FormErrorText(message: errorMessage) }
                    }
                    .padding(AppTheme.Spacing.l)
                }
                .scrollBounceBehavior(.basedOnSize)
            }
            .navigationTitle("Delete Tag")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button { dismiss() } label: { Image(systemName: "xmark") }
                        .accessibilityLabel("Cancel")
                }
            }
            .safeAreaInset(edge: .bottom) {
                DestructiveActionButton(
                    title: "Delete and Re-tag", isEnabled: destination != nil && !isSaving
                ) {
                    Task { await prune() }
                }
                .padding(.horizontal, AppTheme.Spacing.l)
                .padding(.bottom, AppTheme.Spacing.m)
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.s) {
            HStack(spacing: AppTheme.Spacing.s) {
                TagChip(name: tag.name)
                Image(systemName: "arrow.right")
                    .font(AppTheme.Typography.micro)
                    .foregroundStyle(AppTheme.Palette.textSecondary)
                if let destination {
                    TagChip(name: destination.name)
                } else {
                    TagChip(name: "Choose a tag", isFilled: false)
                }
            }

            Text(
                "Every transaction wearing \"\(tag.name)\" will wear the tag you choose instead. "
                    + "Nothing else about those transactions changes."
            )
            .font(AppTheme.Typography.caption)
            .foregroundStyle(AppTheme.Palette.textSecondary)
            .fixedSize(horizontal: false, vertical: true)
        }
    }

    @ViewBuilder
    private var picker: some View {
        if options.isEmpty {
            Text("There's no other tag to move these transactions onto.")
                .font(AppTheme.Typography.caption)
                .foregroundStyle(AppTheme.Palette.textSecondary)
        } else {
            FormCard(padding: AppTheme.Spacing.m) {
                TagFlowLayout(spacing: AppTheme.Spacing.s) {
                    ForEach(options, id: \.id) { option in
                        Button {
                            destination = option
                        } label: {
                            TagChip(name: option.name, isFilled: destination?.id == option.id)
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
        }
    }

    private func prune() async {
        guard let destination else { return }
        isSaving = true
        errorMessage = nil
        do {
            try await HouseholdRepository.deleteTag(
                client: session.client, tagId: tag.id, retaggingInto: destination.id
            )
            await session.syncNow()
            session.refresh.bump()
            onDone()
            dismiss()
        } catch {
            errorMessage = UserFacingError.describe(error)
        }
        isSaving = false
    }
}
